
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fksknsaxzmnajlsrrmyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrc2tuc2F4em1uYWpsc3JybXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDQ5NjksImV4cCI6MjA2MzQ4MDk2OX0.a-up-sfFxdIO8zygMo0UU-D0utjVaw5E13hPheHW10o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
